<div class="container-fluid">
    <div class="contenedor-principal">
        <div class="card-header">
            <h1><?php _e('Cotización'); ?></h1>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <div class="card-header header-titulo">
                        <h3 style="margin:0"><i class="fas fa-cog"></i> <?php _e('Configuraciones') ?></h3>
                    </div>
                    <?php $this->wrpro_presenta_mensaje(); ?>
                    <div class="borde-container">
                        <div class="card-header header-subtitulo"><?php _e('Iniciar numeración de proformas') ?> </div>
                        <div class="card-body">
                            <form action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="POST">
                                <input type='hidden' name='action' value='wrpro_configuraciones'>
                                <input type='hidden' name='numeracion' id="numeracion" value='numeracion_proforma'>
                                <div class="form-group row">
                                    <label for="" class="col-md-3 col-form-label text-md-right"><?php _e('Ingresar número para iniciar proformas:') ?> </label>
                                    <div class="col-md-8">
                                        <input class="form-control" type="number" name="numero_codigo" id="numero_codigo" placeholder="Ingresar número para iniciar proformas" required />
                                    </div>
                                </div>
                                <div class="form-group row mb-0">
                                    <div class="col-md-3 offset-md-3">
                                        <button type="submit" name="registrar" class="btn btn-success btn-block"> <i class="fas fa-save"></i> <?php _e('Aceptar') ?></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="borde-container">
                        <div class="card-header header-subtitulo"> <?php _e('IVA') ?></div>
                        <div class="card-body">
                            <form action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="POST">
                                <input type='hidden' name='action' value='wrpro_configuraciones'>
                                <input type='hidden' name='wr_configuracion' id="wr_configuracion" value='configuracion valores'>
                                <div class="form-group row">
                                    <label for="" class="col-md-3 col-form-label text-md-right"><?php _e('Ingresar valor del IVA:') ?></label>
                                    <div class="col-md-8">
                                        <input class="form-control" type="number" step="0.01" name="valorIva" id="valorIva" placeholder="0.12" value="<?= $valor_iva; ?>" required />
                                        <small><?php _e('IVA Ejm:12% = 0.12'); ?></small>
                                    </div>
                                </div>
                                <div class="form-group row mb-0">
                                    <div class="col-md-3 offset-md-3">
                                        <button type="submit" name="registrar" class="btn btn-success btn-block"> <i class="fas fa-save"></i> <?php _e('Aceptar') ?> </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 ">
                    <p style="font-size: 1em;">
                        <?php printf('En una empresa, las cotizaciones son importantes  porque ayudan con el detalle de los precios y los términos de una transacción propuesta. Por lo general, se utiliza en el contexto de una empresa o negocio que ofrece productos o servicios a sus clientes.') ?>
                    </p>
                    <hr style="border: 2px solid #b8ebe0;">
                    <div class="text-center">
                        <span style="color:#abdfbe;font-size:20em;">
                            <i class="fas fa-file-invoice-dollar"></i>
                        </span>
                    </div>
                </div>
            </div>
            <hr>
        </div>
    </div>
</div>